SELECT 
    ID_CAR,
    DATE_COL,
    MILEAGE,
    REFERENCE,
    LAG (MILEAGE,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) - MILEAGE AS interval_mlg,
    LAG (DATE_COL,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) - DATE_COL AS interval_day
FROM MAINTENANCE
ORDER BY DATE_COL DESC;

SELECT
	ID_MAINTENANCE,
    ID_CAR,
    DATE_COL,
    MILEAGE,
    REFERENCE,
    MILEAGE - LEAD (MILEAGE,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) AS interval_mlg,
    DATE_COL - LEAD (DATE_COL,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) AS interval_day
FROM MAINTENANCE
ORDER BY DATE_COL DESC;

UPDATE MAINTENANCE
SET INTERVAL_COL = (SELECT interval_day FROM 
					(SELECT
						ID_MAINTENANCE,
					    ID_CAR,
					    DATE_COL,
					    MILEAGE,
					    REFERENCE,
					    MILEAGE - LEAD (MILEAGE,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) AS interval_mlg,
					    DATE_COL - LEAD (DATE_COL,1) OVER (PARTITION BY ID_CAR, REFERENCE ORDER BY DATE_COL DESC) AS interval_day
					FROM MAINTENANCE
					ORDER BY DATE_COL DESC) mn
					WHERE mn.ID_MAINTENACE = ID_MAINTENACE ) m
					
SELECT * FROM MAINTENANCE WHERE INTERVAL_COL IS NOT NULL AND INTERVAL_DAYS IS NULL AND ID_CAR = 31;