CREATE OR REPLACE VIEW CARS.FUEL_MILEAGE (ID_FUEL,MLG_OLD,MLG_NEW)
AS
    SELECT ID_FUEL, MILEAGE, diff FROM (
        SELECT
        ID_FUEL,
        MILEAGE,
        LAG(KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_COL DESC) - km AS diff
        FROM CARS.FUEL) cf
        WHERE MILEAGE != diff
        AND ID_FUEL >1900